// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXuv5ITwDkTc_z2iEX6yNRtQcfxdKBUhY',
    appId: '1:234239067291:web:c86bc27d5f586d5b3a723e',
    messagingSenderId: '234239067291',
    projectId: 'proxima-2c9ce',
    authDomain: 'proxima-2c9ce.firebaseapp.com',
    storageBucket: 'proxima-2c9ce.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBimf4iXiBYuPj9kwZkRUDbUU7ddhqOVC0',
    appId: '1:234239067291:android:5abd13f198d4f1113a723e',
    messagingSenderId: '234239067291',
    projectId: 'proxima-2c9ce',
    storageBucket: 'proxima-2c9ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5kgP-8W4fzBN7nOwPkbcPcWwRLk1U8_Y',
    appId: '1:234239067291:ios:eba4fa5a919f42f33a723e',
    messagingSenderId: '234239067291',
    projectId: 'proxima-2c9ce',
    storageBucket: 'proxima-2c9ce.firebasestorage.app',
    iosBundleId: 'me.kriperi.proxima',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5kgP-8W4fzBN7nOwPkbcPcWwRLk1U8_Y',
    appId: '1:234239067291:ios:eba4fa5a919f42f33a723e',
    messagingSenderId: '234239067291',
    projectId: 'proxima-2c9ce',
    storageBucket: 'proxima-2c9ce.firebasestorage.app',
    iosBundleId: 'me.kriperi.proxima',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXuv5ITwDkTc_z2iEX6yNRtQcfxdKBUhY',
    appId: '1:234239067291:web:79ec9bbf61191a103a723e',
    messagingSenderId: '234239067291',
    projectId: 'proxima-2c9ce',
    authDomain: 'proxima-2c9ce.firebaseapp.com',
    storageBucket: 'proxima-2c9ce.firebasestorage.app',
  );
}
